"""Actualizar estructura

Revision ID: fd708cf89b26
Revises: 590e5fe890ea
Create Date: 2021-12-20 16:26:29.171928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd708cf89b26'
down_revision = '590e5fe890ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
